### ISSUE TITLE
how can i use this widget

### ISSUE THREAD

**Issue by sunjiahao4018** [znry27/open_in_new_tab#1]
hello
i install this module, but it not take effect
![image](https://user-images.githubusercontent.com/23587414/117751261-5c8b7e80-b247-11eb-9efc-aebcfc97fee4.png)
![image](https://user-images.githubusercontent.com/23587414/117751438-b3915380-b247-11eb-86c6-7cb8c1783c83.png)
what should i do?
thanks!

**Comment by sunjiahao4018** [comment]
sorry, i find it take effect in form ,but not in views

**Comment by znry27** [comment]
Make sure you use odoo v13 or v14, I don't test this module on odoo v12 or earlier version. In Form view just right-click on the Many2one or Many2many field, then select the **Open link in new tab**. 

In Tree/List view you must right-click the external link icon located on the left side of Tree/List view, then select **Open link in new tab**. But it not applicable for Tree/List view inside a Form view.

Can you use the English language on the browser? I can not read the Chinese character, so I can not give you the suggestion based on your picture.

**Comment by sunjiahao4018** [comment]
Oh, I see
thank you very much
