### ISSUE TITLE
Unwanted indent when using group_by in tree views

### ISSUE THREAD

**Issue by clementmbr** [znry27/open_in_new_tab#2]
Hi @znry27 !
First of all, thank you very much for this very handful module. It was very frustrating not to be able to right-click on these objects ! :)

I just noticed than when we group some lines in tree views there is a mismatch between the values in the groups lines and the lines themselves :
![image](https://user-images.githubusercontent.com/31664455/140031887-cbb25846-cc73-4b52-a481-83480e25d7de.png)

Is it a known issue?
I'm not at all a JS expert, but do you think it is something easy to fix? 

Thanks again ! :pray:

**Comment by znry27** [comment]
I have fixed it. Please check.

**Comment by clementmbr** [comment]
Woa! Thanks for the super quick fix. I just found a small error and made an easy PR to solves it : #3

**Comment by rvalyi** [comment]
this issue can be closed then.
